FROM python:2.7 as base

ENV LANG "en_US.UTF-8"
ENV LANG C.UTF-8
ENV LC_ALL "en_US.UTF-8"
ENV LC_ALL C.UTF-8
ENV PYTHONUNBUFFERED 1


WORKDIR /app
COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

